spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/lunch-manager-bot-db
    username: admin
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 67000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximum-pool-size: 20
      leak-detection-threshold: 90000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:/db/migration,/db/data
    baseline-on-migrate: true
    validate-on-migrate: false
