management:
  endpoints:
    web:
      exposure:
        include: 'prometheus, health'
      base-path: /monitoring
  endpoint:
    shutdown.enabled: true
    health:
      show-components: always
      show-details: always
      probes.enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
