global:
  scrape_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'promq-graf-service'
    scrape_interval: 5s
    metrics_path: '/monitoring/prometheus'
    static_configs:
      - targets: ['lunch-manager-bot-service:8081']